Update rubocop config for ruby 3.2
wtag/default-configs pull request #5
Opened 2023-12-04 04:02 UTC by nal-wtag

2023-12-04 18:13 UTC, luxflux requested changes

2023-12-04 18:13 UTC, luxflux commented on rubocop-default-config-ruby3.2.yml
> +  NewCops: enable
As it inherits from 2.6, I think this can be further simplified:
```suggestion
  TargetRubyVersion: 3.2
```

2023-12-12 08:59 UTC, yra-wtag approved these changes
LGTM, please fix according raffael bhai's comment

2023-12-12 18:28 UTC, luxflux approved these changes

2023-12-21 08:27 UTC, merged